sudo: required
language:
    - python
    - c
python: "3.5"
compiler: gcc clang
install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq doxygen libtool automake autoconf
    - sudo python -m pip install pytest
script:
    - ./makeconf.sh
    - ./configure
    - make -j4
    - doxygen doc/Doxyfile
    - python -m pytest test/
    - make clean
    - make -j4 CC=clang CFLAGS="-fsanitize=address -g -O1"
    - python -m pytest test/
    - make clean
    - make -j4 CC=clang CFLAGS="-fsanitize=thread,undefined -g -O1"
    - python -m pytest test/

