sudo: required
language:
    - python
    - c
python: "3.5"
compiler:
    - gcc
    - clang
env:
    - CC=gcc-6
    - CC=clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - doxygen
    - libtool
    - automake
    - autoconf
    - gcc-6
install:
    - sudo python -m pip install pytest
script:
    - $CC --version
    - ./makeconf.sh
    - ./configure
    - CFLAGS="-fsanitize=address,undefined -g -O1 -Wall -Werror" make
    - doxygen doc/Doxyfile
    - python -m pytest test/
